name: Run Frontend Tests
on:
  pull_request:
  push:
    branches:
      - staging
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run Jest tests
        run: npm test

      - name: Build app
        run: npm run build
